eureka:
  instance:
    hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

server:
  port: 8090

spring:
  application:
    name: schools
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: ghaith
    password: ghaith
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    student-url: http://localhost:8070/api/v1/students