eureka:
  instance:
    hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

server:
  port: 8070

spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/students
    username: ghaith
    password: ghaith
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0

